# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Working/cmlib/cmMayaWorkgroup2020/mGear/scripts/mgear/shifter_classic_components/ui_host_01/settingsUI.ui',
# licensing of 'D:/Working/cmlib/cmMayaWorkgroup2020/mGear/scripts/mgear/shifter_classic_components/ui_host_01/settingsUI.ui' applies.
#
# Created: Thu Dec  2 15:38:37 2021
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(347, 570)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ctlSize_label = QtWidgets.QLabel(self.groupBox)
        self.ctlSize_label.setObjectName("ctlSize_label")
        self.gridLayout_2.addWidget(self.ctlSize_label, 1, 0, 1, 1)
        self.ctlSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlSize_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlSize_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlSize_doubleSpinBox.setWrapping(False)
        self.ctlSize_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlSize_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlSize_doubleSpinBox.setMinimum(0.01)
        self.ctlSize_doubleSpinBox.setMaximum(20000.0)
        self.ctlSize_doubleSpinBox.setProperty("value", 1.0)
        self.ctlSize_doubleSpinBox.setObjectName("ctlSize_doubleSpinBox")
        self.gridLayout_2.addWidget(self.ctlSize_doubleSpinBox, 1, 1, 1, 1)
        self.neutralRotation_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.neutralRotation_checkBox.setObjectName("neutralRotation_checkBox")
        self.gridLayout_2.addWidget(self.neutralRotation_checkBox, 0, 0, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlShape_label = QtWidgets.QLabel(self.groupBox)
        self.controlShape_label.setText("Control Shape")
        self.controlShape_label.setObjectName("controlShape_label")
        self.horizontalLayout_2.addWidget(self.controlShape_label)
        self.controlShape_comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlShape_comboBox.sizePolicy().hasHeightForWidth())
        self.controlShape_comboBox.setSizePolicy(sizePolicy)
        self.controlShape_comboBox.setObjectName("controlShape_comboBox")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.controlShape_comboBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.controlShape_label_2 = QtWidgets.QLabel(self.groupBox)
        self.controlShape_label_2.setText("Host Type")
        self.controlShape_label_2.setObjectName("controlShape_label_2")
        self.horizontalLayout_4.addWidget(self.controlShape_label_2)
        self.uiType_comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uiType_comboBox.sizePolicy().hasHeightForWidth())
        self.uiType_comboBox.setSizePolicy(sizePolicy)
        self.uiType_comboBox.setObjectName("uiType_comboBox")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.uiType_comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.uiType_comboBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.keyable_groupBox = QtWidgets.QGroupBox(Form)
        self.keyable_groupBox.setObjectName("keyable_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.keyable_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.translate_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.translate_pushButton.setObjectName("translate_pushButton")
        self.verticalLayout.addWidget(self.translate_pushButton)
        self.tx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.tx_checkBox.setObjectName("tx_checkBox")
        self.verticalLayout.addWidget(self.tx_checkBox)
        self.ty_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ty_checkBox.setObjectName("ty_checkBox")
        self.verticalLayout.addWidget(self.ty_checkBox)
        self.tz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.tz_checkBox.setObjectName("tz_checkBox")
        self.verticalLayout.addWidget(self.tz_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rotate_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_2.addWidget(self.rotate_pushButton)
        self.rx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.rx_checkBox.setObjectName("rx_checkBox")
        self.verticalLayout_2.addWidget(self.rx_checkBox)
        self.ry_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ry_checkBox.setObjectName("ry_checkBox")
        self.verticalLayout_2.addWidget(self.ry_checkBox)
        self.rz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.rz_checkBox.setObjectName("rz_checkBox")
        self.verticalLayout_2.addWidget(self.rz_checkBox)
        self.ro_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ro_checkBox.setObjectName("ro_checkBox")
        self.verticalLayout_2.addWidget(self.ro_checkBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scale_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.scale_pushButton.setObjectName("scale_pushButton")
        self.verticalLayout_3.addWidget(self.scale_pushButton)
        self.sx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sx_checkBox.setObjectName("sx_checkBox")
        self.verticalLayout_3.addWidget(self.sx_checkBox)
        self.sy_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sy_checkBox.setObjectName("sy_checkBox")
        self.verticalLayout_3.addWidget(self.sy_checkBox)
        self.sz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sz_checkBox.setObjectName("sz_checkBox")
        self.verticalLayout_3.addWidget(self.sz_checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.keyable_groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.tx_checkBox.toggle)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.ty_checkBox.toggle)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.tz_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.rx_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.ry_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.rz_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.ro_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sx_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sy_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sz_checkBox.toggle)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.ctlSize_label.setText(QtWidgets.QApplication.translate("Form", "Ctl Size", None, -1))
        self.neutralRotation_checkBox.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>If is active, it will align the control with world space</p></body></html>", None, -1))
        self.neutralRotation_checkBox.setText(QtWidgets.QApplication.translate("Form", "World Space Orientation Align", None, -1))
        self.controlShape_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Arrow", None, -1))
        self.controlShape_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Circle", None, -1))
        self.controlShape_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Compas", None, -1))
        self.controlShape_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "Cross", None, -1))
        self.controlShape_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "Crossarrow", None, -1))
        self.controlShape_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "Cube", None, -1))
        self.controlShape_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "Cubewithpeak", None, -1))
        self.controlShape_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "Cylinder", None, -1))
        self.controlShape_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "Diamond", None, -1))
        self.controlShape_comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "Flower", None, -1))
        self.controlShape_comboBox.setItemText(10, QtWidgets.QApplication.translate("Form", "Null", None, -1))
        self.controlShape_comboBox.setItemText(11, QtWidgets.QApplication.translate("Form", "Pyramid", None, -1))
        self.controlShape_comboBox.setItemText(12, QtWidgets.QApplication.translate("Form", "Sphere", None, -1))
        self.controlShape_comboBox.setItemText(13, QtWidgets.QApplication.translate("Form", "Square", None, -1))
        self.uiType_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Arm", None, -1))
        self.uiType_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Leg", None, -1))
        self.uiType_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Spine", None, -1))
        self.uiType_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "Face", None, -1))
        self.uiType_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "Cape", None, -1))
        self.uiType_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "Tail", None, -1))
        self.uiType_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "Wing", None, -1))
        self.uiType_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "Car", None, -1))
        self.uiType_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "Misc", None, -1))
        self.keyable_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Keyable", None, -1))
        self.translate_pushButton.setText(QtWidgets.QApplication.translate("Form", "Translate", None, -1))
        self.tx_checkBox.setText(QtWidgets.QApplication.translate("Form", "tx", None, -1))
        self.ty_checkBox.setText(QtWidgets.QApplication.translate("Form", "ty", None, -1))
        self.tz_checkBox.setText(QtWidgets.QApplication.translate("Form", "tz", None, -1))
        self.rotate_pushButton.setText(QtWidgets.QApplication.translate("Form", "Rotate", None, -1))
        self.rx_checkBox.setText(QtWidgets.QApplication.translate("Form", "rx", None, -1))
        self.ry_checkBox.setText(QtWidgets.QApplication.translate("Form", "ry", None, -1))
        self.rz_checkBox.setText(QtWidgets.QApplication.translate("Form", "rz", None, -1))
        self.ro_checkBox.setText(QtWidgets.QApplication.translate("Form", "ro", None, -1))
        self.scale_pushButton.setText(QtWidgets.QApplication.translate("Form", "Scale", None, -1))
        self.sx_checkBox.setText(QtWidgets.QApplication.translate("Form", "sx", None, -1))
        self.sy_checkBox.setText(QtWidgets.QApplication.translate("Form", "sy", None, -1))
        self.sz_checkBox.setText(QtWidgets.QApplication.translate("Form", "sz", None, -1))

