# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Working/cmlib/dev/git/mgear_dev/mgear3/scripts/mgear/shifter_classic_components/veh_chassis_01/settingsUI.ui',
# licensing of 'D:/Working/cmlib/dev/git/mgear_dev/mgear3/scripts/mgear/shifter_classic_components/veh_chassis_01/settingsUI.ui' applies.
#
# Created: Wed Feb 16 15:18:24 2022
#      by: pyside2-uic  running on PySide2 5.12.5
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(347, 1008)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.ikRefArrayRF_groupBox = QtWidgets.QGroupBox(Form)
        self.ikRefArrayRF_groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ikRefArrayRF_groupBox.setObjectName("ikRefArrayRF_groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ikRefArrayRF_groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.ikRefArray_horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout_3.setObjectName("ikRefArray_horizontalLayout_3")
        self.ikRefArray_verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_5.setObjectName("ikRefArray_verticalLayout_5")
        self.ikRefArrayRF_listWidget = QtWidgets.QListWidget(self.ikRefArrayRF_groupBox)
        self.ikRefArrayRF_listWidget.setDragDropOverwriteMode(True)
        self.ikRefArrayRF_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ikRefArrayRF_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ikRefArrayRF_listWidget.setAlternatingRowColors(True)
        self.ikRefArrayRF_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ikRefArrayRF_listWidget.setSelectionRectVisible(False)
        self.ikRefArrayRF_listWidget.setObjectName("ikRefArrayRF_listWidget")
        self.ikRefArray_verticalLayout_5.addWidget(self.ikRefArrayRF_listWidget)
        self.ikRefArray_horizontalLayout_3.addLayout(self.ikRefArray_verticalLayout_5)
        self.ikRefArray_verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_6.setObjectName("ikRefArray_verticalLayout_6")
        self.ikRefArrayAddRF_pushButton = QtWidgets.QPushButton(self.ikRefArrayRF_groupBox)
        self.ikRefArrayAddRF_pushButton.setObjectName("ikRefArrayAddRF_pushButton")
        self.ikRefArray_verticalLayout_6.addWidget(self.ikRefArrayAddRF_pushButton)
        self.ikRefArrayRemoveRF_pushButton = QtWidgets.QPushButton(self.ikRefArrayRF_groupBox)
        self.ikRefArrayRemoveRF_pushButton.setObjectName("ikRefArrayRemoveRF_pushButton")
        self.ikRefArray_verticalLayout_6.addWidget(self.ikRefArrayRemoveRF_pushButton)
        self.ikRefArray_horizontalLayout_3.addLayout(self.ikRefArray_verticalLayout_6)
        self.gridLayout_6.addLayout(self.ikRefArray_horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ikRefArrayRF_groupBox, 4, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.joint_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.joint_checkBox.setObjectName("joint_checkBox")
        self.verticalLayout_4.addWidget(self.joint_checkBox)
        self.uniScale_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.uniScale_checkBox.setObjectName("uniScale_checkBox")
        self.verticalLayout_4.addWidget(self.uniScale_checkBox)
        self.neutralRotation_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.neutralRotation_checkBox.setObjectName("neutralRotation_checkBox")
        self.verticalLayout_4.addWidget(self.neutralRotation_checkBox)
        self.mirrorBehaviour_checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.mirrorBehaviour_checkBox.setObjectName("mirrorBehaviour_checkBox")
        self.verticalLayout_4.addWidget(self.mirrorBehaviour_checkBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ctlSize_label = QtWidgets.QLabel(self.groupBox)
        self.ctlSize_label.setObjectName("ctlSize_label")
        self.horizontalLayout_3.addWidget(self.ctlSize_label)
        self.ctlSize_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctlSize_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.ctlSize_doubleSpinBox.setSizePolicy(sizePolicy)
        self.ctlSize_doubleSpinBox.setWrapping(False)
        self.ctlSize_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.ctlSize_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.ctlSize_doubleSpinBox.setMinimum(0.01)
        self.ctlSize_doubleSpinBox.setMaximum(20000.0)
        self.ctlSize_doubleSpinBox.setProperty("value", 1.0)
        self.ctlSize_doubleSpinBox.setObjectName("ctlSize_doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.ctlSize_doubleSpinBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.controlShape_label = QtWidgets.QLabel(self.groupBox)
        self.controlShape_label.setText("Control Shape")
        self.controlShape_label.setObjectName("controlShape_label")
        self.horizontalLayout_2.addWidget(self.controlShape_label)
        self.controlShape_comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlShape_comboBox.sizePolicy().hasHeightForWidth())
        self.controlShape_comboBox.setSizePolicy(sizePolicy)
        self.controlShape_comboBox.setObjectName("controlShape_comboBox")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.controlShape_comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.controlShape_comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.ikRefArrayLR_groupBox = QtWidgets.QGroupBox(Form)
        self.ikRefArrayLR_groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ikRefArrayLR_groupBox.setObjectName("ikRefArrayLR_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ikRefArrayLR_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ikRefArray_horizontalLayout = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout.setObjectName("ikRefArray_horizontalLayout")
        self.ikRefArray_verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_1.setObjectName("ikRefArray_verticalLayout_1")
        self.ikRefArrayLR_listWidget = QtWidgets.QListWidget(self.ikRefArrayLR_groupBox)
        self.ikRefArrayLR_listWidget.setDragDropOverwriteMode(True)
        self.ikRefArrayLR_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ikRefArrayLR_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ikRefArrayLR_listWidget.setAlternatingRowColors(True)
        self.ikRefArrayLR_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ikRefArrayLR_listWidget.setSelectionRectVisible(False)
        self.ikRefArrayLR_listWidget.setObjectName("ikRefArrayLR_listWidget")
        self.ikRefArray_verticalLayout_1.addWidget(self.ikRefArrayLR_listWidget)
        self.ikRefArray_horizontalLayout.addLayout(self.ikRefArray_verticalLayout_1)
        self.ikRefArray_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_2.setObjectName("ikRefArray_verticalLayout_2")
        self.ikRefArrayAddLR_pushButton = QtWidgets.QPushButton(self.ikRefArrayLR_groupBox)
        self.ikRefArrayAddLR_pushButton.setObjectName("ikRefArrayAddLR_pushButton")
        self.ikRefArray_verticalLayout_2.addWidget(self.ikRefArrayAddLR_pushButton)
        self.ikRefArrayRemoveLR_pushButton = QtWidgets.QPushButton(self.ikRefArrayLR_groupBox)
        self.ikRefArrayRemoveLR_pushButton.setObjectName("ikRefArrayRemoveLR_pushButton")
        self.ikRefArray_verticalLayout_2.addWidget(self.ikRefArrayRemoveLR_pushButton)
        self.ikRefArray_horizontalLayout.addLayout(self.ikRefArray_verticalLayout_2)
        self.gridLayout_3.addLayout(self.ikRefArray_horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ikRefArrayLR_groupBox, 2, 0, 1, 1)
        self.keyable_groupBox = QtWidgets.QGroupBox(Form)
        self.keyable_groupBox.setObjectName("keyable_groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.keyable_groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.translate_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.translate_pushButton.setObjectName("translate_pushButton")
        self.verticalLayout.addWidget(self.translate_pushButton)
        self.tx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.tx_checkBox.setObjectName("tx_checkBox")
        self.verticalLayout.addWidget(self.tx_checkBox)
        self.ty_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ty_checkBox.setObjectName("ty_checkBox")
        self.verticalLayout.addWidget(self.ty_checkBox)
        self.tz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.tz_checkBox.setObjectName("tz_checkBox")
        self.verticalLayout.addWidget(self.tz_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rotate_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_2.addWidget(self.rotate_pushButton)
        self.rx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.rx_checkBox.setObjectName("rx_checkBox")
        self.verticalLayout_2.addWidget(self.rx_checkBox)
        self.ry_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ry_checkBox.setObjectName("ry_checkBox")
        self.verticalLayout_2.addWidget(self.ry_checkBox)
        self.rz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.rz_checkBox.setObjectName("rz_checkBox")
        self.verticalLayout_2.addWidget(self.rz_checkBox)
        self.ro_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.ro_checkBox.setObjectName("ro_checkBox")
        self.verticalLayout_2.addWidget(self.ro_checkBox)
        self.ro_comboBox = QtWidgets.QComboBox(self.keyable_groupBox)
        self.ro_comboBox.setObjectName("ro_comboBox")
        self.ro_comboBox.addItem("")
        self.ro_comboBox.addItem("")
        self.ro_comboBox.addItem("")
        self.ro_comboBox.addItem("")
        self.ro_comboBox.addItem("")
        self.ro_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.ro_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scale_pushButton = QtWidgets.QPushButton(self.keyable_groupBox)
        self.scale_pushButton.setObjectName("scale_pushButton")
        self.verticalLayout_3.addWidget(self.scale_pushButton)
        self.sx_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sx_checkBox.setObjectName("sx_checkBox")
        self.verticalLayout_3.addWidget(self.sx_checkBox)
        self.sy_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sy_checkBox.setObjectName("sy_checkBox")
        self.verticalLayout_3.addWidget(self.sy_checkBox)
        self.sz_checkBox = QtWidgets.QCheckBox(self.keyable_groupBox)
        self.sz_checkBox.setObjectName("sz_checkBox")
        self.verticalLayout_3.addWidget(self.sz_checkBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.keyable_groupBox, 1, 0, 1, 1)
        self.ikRefArrayRR_groupBox = QtWidgets.QGroupBox(Form)
        self.ikRefArrayRR_groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ikRefArrayRR_groupBox.setObjectName("ikRefArrayRR_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ikRefArrayRR_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ikRefArray_horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout_4.setObjectName("ikRefArray_horizontalLayout_4")
        self.ikRefArray_verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_7.setObjectName("ikRefArray_verticalLayout_7")
        self.ikRefArrayRR_listWidget = QtWidgets.QListWidget(self.ikRefArrayRR_groupBox)
        self.ikRefArrayRR_listWidget.setDragDropOverwriteMode(True)
        self.ikRefArrayRR_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ikRefArrayRR_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ikRefArrayRR_listWidget.setAlternatingRowColors(True)
        self.ikRefArrayRR_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ikRefArrayRR_listWidget.setSelectionRectVisible(False)
        self.ikRefArrayRR_listWidget.setObjectName("ikRefArrayRR_listWidget")
        self.ikRefArray_verticalLayout_7.addWidget(self.ikRefArrayRR_listWidget)
        self.ikRefArray_horizontalLayout_4.addLayout(self.ikRefArray_verticalLayout_7)
        self.ikRefArray_verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_8.setObjectName("ikRefArray_verticalLayout_8")
        self.ikRefArrayAddRR_pushButton = QtWidgets.QPushButton(self.ikRefArrayRR_groupBox)
        self.ikRefArrayAddRR_pushButton.setObjectName("ikRefArrayAddRR_pushButton")
        self.ikRefArray_verticalLayout_8.addWidget(self.ikRefArrayAddRR_pushButton)
        self.ikRefArrayRemoveRR_pushButton = QtWidgets.QPushButton(self.ikRefArrayRR_groupBox)
        self.ikRefArrayRemoveRR_pushButton.setObjectName("ikRefArrayRemoveRR_pushButton")
        self.ikRefArray_verticalLayout_8.addWidget(self.ikRefArrayRemoveRR_pushButton)
        self.ikRefArray_horizontalLayout_4.addLayout(self.ikRefArray_verticalLayout_8)
        self.gridLayout_7.addLayout(self.ikRefArray_horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ikRefArrayRR_groupBox, 5, 0, 1, 1)
        self.ikRefArrayLF_groupBox = QtWidgets.QGroupBox(Form)
        self.ikRefArrayLF_groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.ikRefArrayLF_groupBox.setObjectName("ikRefArrayLF_groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ikRefArrayLF_groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ikRefArray_horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout_2.setObjectName("ikRefArray_horizontalLayout_2")
        self.ikRefArray_verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_3.setObjectName("ikRefArray_verticalLayout_3")
        self.ikRefArrayLF_listWidget = QtWidgets.QListWidget(self.ikRefArrayLF_groupBox)
        self.ikRefArrayLF_listWidget.setDragDropOverwriteMode(True)
        self.ikRefArrayLF_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.ikRefArrayLF_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.ikRefArrayLF_listWidget.setAlternatingRowColors(True)
        self.ikRefArrayLF_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ikRefArrayLF_listWidget.setSelectionRectVisible(False)
        self.ikRefArrayLF_listWidget.setObjectName("ikRefArrayLF_listWidget")
        self.ikRefArray_verticalLayout_3.addWidget(self.ikRefArrayLF_listWidget)
        self.ikRefArray_horizontalLayout_2.addLayout(self.ikRefArray_verticalLayout_3)
        self.ikRefArray_verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_4.setObjectName("ikRefArray_verticalLayout_4")
        self.ikRefArrayAddLF_pushButton = QtWidgets.QPushButton(self.ikRefArrayLF_groupBox)
        self.ikRefArrayAddLF_pushButton.setObjectName("ikRefArrayAddLF_pushButton")
        self.ikRefArray_verticalLayout_4.addWidget(self.ikRefArrayAddLF_pushButton)
        self.ikRefArrayRemoveLF_pushButton = QtWidgets.QPushButton(self.ikRefArrayLF_groupBox)
        self.ikRefArrayRemoveLF_pushButton.setObjectName("ikRefArrayRemoveLF_pushButton")
        self.ikRefArray_verticalLayout_4.addWidget(self.ikRefArrayRemoveLF_pushButton)
        self.ikRefArray_horizontalLayout_2.addLayout(self.ikRefArray_verticalLayout_4)
        self.gridLayout_5.addLayout(self.ikRefArray_horizontalLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ikRefArrayLF_groupBox, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(158, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.globalScaleArray_groupBox = QtWidgets.QGroupBox(Form)
        self.globalScaleArray_groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.globalScaleArray_groupBox.setObjectName("globalScaleArray_groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.globalScaleArray_groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.ikRefArray_horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.ikRefArray_horizontalLayout_5.setObjectName("ikRefArray_horizontalLayout_5")
        self.ikRefArray_verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_9.setObjectName("ikRefArray_verticalLayout_9")
        self.globalScaleArray_listWidget = QtWidgets.QListWidget(self.globalScaleArray_groupBox)
        self.globalScaleArray_listWidget.setDragDropOverwriteMode(True)
        self.globalScaleArray_listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.globalScaleArray_listWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.globalScaleArray_listWidget.setAlternatingRowColors(True)
        self.globalScaleArray_listWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.globalScaleArray_listWidget.setSelectionRectVisible(False)
        self.globalScaleArray_listWidget.setObjectName("globalScaleArray_listWidget")
        self.ikRefArray_verticalLayout_9.addWidget(self.globalScaleArray_listWidget)
        self.ikRefArray_horizontalLayout_5.addLayout(self.ikRefArray_verticalLayout_9)
        self.ikRefArray_verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.ikRefArray_verticalLayout_10.setObjectName("ikRefArray_verticalLayout_10")
        self.globalArrayAdd_pushButton = QtWidgets.QPushButton(self.globalScaleArray_groupBox)
        self.globalArrayAdd_pushButton.setObjectName("globalArrayAdd_pushButton")
        self.ikRefArray_verticalLayout_10.addWidget(self.globalArrayAdd_pushButton)
        self.globalArrayRemove_pushButton = QtWidgets.QPushButton(self.globalScaleArray_groupBox)
        self.globalArrayRemove_pushButton.setObjectName("globalArrayRemove_pushButton")
        self.ikRefArray_verticalLayout_10.addWidget(self.globalArrayRemove_pushButton)
        self.ikRefArray_horizontalLayout_5.addLayout(self.ikRefArray_verticalLayout_10)
        self.gridLayout_8.addLayout(self.ikRefArray_horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.globalScaleArray_groupBox, 6, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.tx_checkBox.toggle)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.ty_checkBox.toggle)
        QtCore.QObject.connect(self.translate_pushButton, QtCore.SIGNAL("clicked()"), self.tz_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.rx_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.ry_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.rz_checkBox.toggle)
        QtCore.QObject.connect(self.rotate_pushButton, QtCore.SIGNAL("clicked()"), self.ro_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sx_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sy_checkBox.toggle)
        QtCore.QObject.connect(self.scale_pushButton, QtCore.SIGNAL("clicked()"), self.sz_checkBox.toggle)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.ikRefArrayRF_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "IK Reference Right Front", None, -1))
        self.ikRefArrayAddRF_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.ikRefArrayRemoveRF_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.joint_checkBox.setText(QtWidgets.QApplication.translate("Form", "Joint", None, -1))
        self.uniScale_checkBox.setText(QtWidgets.QApplication.translate("Form", "Uniform Scale", None, -1))
        self.neutralRotation_checkBox.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>If is active, it will align the control with world space</p></body></html>", None, -1))
        self.neutralRotation_checkBox.setText(QtWidgets.QApplication.translate("Form", "World Space Orientation Align", None, -1))
        self.mirrorBehaviour_checkBox.setToolTip(QtWidgets.QApplication.translate("Form", "<html><head/><body><p>If is active, the control will have symmetrical behaviour on Left and Right side.</p><p><br/></p><p>WARNING: There is a bug in Maya 2018 and 2018.1 that will result in an incorrect behaviour, because this option will negate one of the axis. Other Maya version should be ok.</p></body></html>", None, -1))
        self.mirrorBehaviour_checkBox.setText(QtWidgets.QApplication.translate("Form", "Mirror Behaviour L and R", None, -1))
        self.ctlSize_label.setText(QtWidgets.QApplication.translate("Form", "Ctl Size", None, -1))
        self.controlShape_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "Arrow", None, -1))
        self.controlShape_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "Circle", None, -1))
        self.controlShape_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "Compas", None, -1))
        self.controlShape_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "Cross", None, -1))
        self.controlShape_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "Crossarrow", None, -1))
        self.controlShape_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "Cube", None, -1))
        self.controlShape_comboBox.setItemText(6, QtWidgets.QApplication.translate("Form", "Cubewithpeak", None, -1))
        self.controlShape_comboBox.setItemText(7, QtWidgets.QApplication.translate("Form", "Cylinder", None, -1))
        self.controlShape_comboBox.setItemText(8, QtWidgets.QApplication.translate("Form", "Diamond", None, -1))
        self.controlShape_comboBox.setItemText(9, QtWidgets.QApplication.translate("Form", "Flower", None, -1))
        self.controlShape_comboBox.setItemText(10, QtWidgets.QApplication.translate("Form", "Null", None, -1))
        self.controlShape_comboBox.setItemText(11, QtWidgets.QApplication.translate("Form", "Pyramid", None, -1))
        self.controlShape_comboBox.setItemText(12, QtWidgets.QApplication.translate("Form", "Sphere", None, -1))
        self.controlShape_comboBox.setItemText(13, QtWidgets.QApplication.translate("Form", "Square", None, -1))
        self.ikRefArrayLR_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "IK Reference Left Rear", None, -1))
        self.ikRefArrayAddLR_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.ikRefArrayRemoveLR_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.keyable_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Keyable", None, -1))
        self.translate_pushButton.setText(QtWidgets.QApplication.translate("Form", "Translate", None, -1))
        self.tx_checkBox.setText(QtWidgets.QApplication.translate("Form", "tx", None, -1))
        self.ty_checkBox.setText(QtWidgets.QApplication.translate("Form", "ty", None, -1))
        self.tz_checkBox.setText(QtWidgets.QApplication.translate("Form", "tz", None, -1))
        self.rotate_pushButton.setText(QtWidgets.QApplication.translate("Form", "Rotate", None, -1))
        self.rx_checkBox.setText(QtWidgets.QApplication.translate("Form", "rx", None, -1))
        self.ry_checkBox.setText(QtWidgets.QApplication.translate("Form", "ry", None, -1))
        self.rz_checkBox.setText(QtWidgets.QApplication.translate("Form", "rz", None, -1))
        self.ro_checkBox.setText(QtWidgets.QApplication.translate("Form", "ro", None, -1))
        self.ro_comboBox.setItemText(0, QtWidgets.QApplication.translate("Form", "XYZ", None, -1))
        self.ro_comboBox.setItemText(1, QtWidgets.QApplication.translate("Form", "YZX", None, -1))
        self.ro_comboBox.setItemText(2, QtWidgets.QApplication.translate("Form", "ZXY", None, -1))
        self.ro_comboBox.setItemText(3, QtWidgets.QApplication.translate("Form", "XZY", None, -1))
        self.ro_comboBox.setItemText(4, QtWidgets.QApplication.translate("Form", "YXZ", None, -1))
        self.ro_comboBox.setItemText(5, QtWidgets.QApplication.translate("Form", "ZYX", None, -1))
        self.scale_pushButton.setText(QtWidgets.QApplication.translate("Form", "Scale", None, -1))
        self.sx_checkBox.setText(QtWidgets.QApplication.translate("Form", "sx", None, -1))
        self.sy_checkBox.setText(QtWidgets.QApplication.translate("Form", "sy", None, -1))
        self.sz_checkBox.setText(QtWidgets.QApplication.translate("Form", "sz", None, -1))
        self.ikRefArrayRR_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "IK Reference Right Rear", None, -1))
        self.ikRefArrayAddRR_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.ikRefArrayRemoveRR_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.ikRefArrayLF_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "IK Reference Left Front", None, -1))
        self.ikRefArrayAddLF_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.ikRefArrayRemoveLF_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))
        self.globalScaleArray_groupBox.setTitle(QtWidgets.QApplication.translate("Form", "Global Scale Obj", None, -1))
        self.globalArrayAdd_pushButton.setText(QtWidgets.QApplication.translate("Form", "<<", None, -1))
        self.globalArrayRemove_pushButton.setText(QtWidgets.QApplication.translate("Form", ">>", None, -1))

